
package Server;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxpayne47
 */
public class ServerGui extends javax.swing.JFrame {
    //****variables***//
    private  ServerSocket Server= null;
    private  Socket Client = null;
    private  boolean isRunning= false;
    private  ExecutorService pool = Executors.newFixedThreadPool(10);
    protected static ArrayList<handdleClient>clients = new ArrayList<>();
    //***************//
       
    /**
     * Creates new form ServerGui
     */
    public ServerGui() {
        initComponents();
        //**inialise the state of widgets to Disabled**//
        stopBtn.setEnabled(false);
        DashList.setEnabled(false);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DashList = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        ChatBot = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        ChatBot1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setResizable(false);

        connectBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        connectBtn.setText("Start");
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });

        stopBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stopBtn.setText("Stop");
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        DashList.setEditable(false);
        DashList.setColumns(20);
        DashList.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DashList.setLineWrap(true);
        DashList.setRows(5);
        DashList.setWrapStyleWord(true);
        DashList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Users", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(DashList);

        jPanel1.setBackground(new java.awt.Color(16, 31, 54));
        jPanel1.setPreferredSize(new java.awt.Dimension(224, 50));

        ChatBot.setBackground(new java.awt.Color(250, 250, 250));
        ChatBot.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        ChatBot.setForeground(new java.awt.Color(250, 250, 250));
        ChatBot.setText("ChatBot v1.0");

        Autor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        Autor.setForeground(new java.awt.Color(250, 250, 250));
        Autor.setText("By ChemsEddine Nemeur");

        ChatBot1.setBackground(new java.awt.Color(250, 250, 250));
        ChatBot1.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        ChatBot1.setForeground(new java.awt.Color(250, 250, 250));
        ChatBot1.setText("Server");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChatBot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(ChatBot1)
                .addGap(71, 71, 71)
                .addComponent(Autor))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ChatBot, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ChatBot1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Autor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(connectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //***Bottons***//
    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
        
        try {
            connectBtn.setEnabled(false);
            stopBtn.setEnabled(true);
            DashList.setText("");
            DashList.setEnabled(true);
            //****Start a new server on Port 9090****//
            Server = new ServerSocket(9090);
            DashList.append("["+LocalTime.now()+"]"+"  Server Stared on Port 9090.\n");
            isRunning = true;
            AcceptHanddle();
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_connectBtnActionPerformed
   
    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
  
        isRunning = false;
        try {
            Server.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        stopBtn.setEnabled(false);
        connectBtn.setEnabled(true);
        DashList.setText("");
        DashList.append("Server Stopped");        
        DashList.setEnabled(false);
    }//GEN-LAST:event_stopBtnActionPerformed
    //****Handdle methode***//
    private void AcceptHanddle(){
        Thread startServer = new Thread("start"){
            public void run(){
                try{
                    while(isRunning){
                        //*****accept clients while server is running****//
                        Client = Server.accept();
                        DashList.append("["+LocalTime.now()+"]"+"  IP:"+Client.getInetAddress().toString().replace("/","")+" PORT:"+Client.getPort()+" connected!\n");
                        //****handlle the client connection (send-recieve) in class handdleClient****//
                        handdleClient thread = new handdleClient(Client);
                        //**add the client to clients List**//
                        clients.add(thread);    
                        pool.execute(thread);  
                        }      
                    }catch(IOException e){
                        if(!(e.getMessage().equals("socket closed"))){
                            JOptionPane.showMessageDialog(null,e.getMessage());
                        }                  
                    }
            }  
        };startServer.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JLabel ChatBot;
    private javax.swing.JLabel ChatBot1;
    public static javax.swing.JTextArea DashList;
    private javax.swing.JButton connectBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton stopBtn;
    // End of variables declaration//GEN-END:variables
}
